##### ❇️ Python matmul operator @

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
arr1 = np.random.rand(3, 3)
arr2 = np.random.rand(3, 3)

##### ❇️ Matrix multiplication before Python 3.5

In [3]:
np.matmul(arr1, arr2)

array([[0.57104228, 0.6249187 , 0.75554827],
       [0.84227088, 0.52005673, 0.96547005],
       [1.51418666, 1.04428351, 1.77612534]])

In [4]:
tf.linalg.matmul(arr1, arr2)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.57104228, 0.6249187 , 0.75554827],
       [0.84227088, 0.52005673, 0.96547005],
       [1.51418666, 1.04428351, 1.77612534]])>

##### ❇️ Matrix multiplication after Python 3.5

In [5]:
arr1@arr2

array([[0.57104228, 0.6249187 , 0.75554827],
       [0.84227088, 0.52005673, 0.96547005],
       [1.51418666, 1.04428351, 1.77612534]])

##### ❇️ Matmul operator can be defined for any class using __ __matmul__ __ dunder.

In [6]:
class CustomInt:
  def __init__(self, val):
    self.val = val
  def __matmul__(self, input_int):
    return self.val**input_int.val

In [7]:
int_1, int_2 = CustomInt(2), CustomInt(3)
int_1@int_2

8

##### ❇️ Hope you enjoyed reading!! 📖 
##### ❇️ follow → @akshay_pachaar  